package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"image"
	"image/jpeg"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"cozyroom/internal/metrics"
	"cozyroom/internal/transcode"
	"cozyroom/internal/usecase"
	xdraw "golang.org/x/image/draw"
	"golang.org/x/sync/singleflight"
)

var coverSF singleflight.Group

type handlers struct {
	lib          *usecase.LibraryUsecase
	lyrics       *usecase.LyricsUsecase
	settings     *usecase.SettingsUsecase
	playback     *usecase.PlaybackUsecase
	scanDB       *sql.DB // only for scanner/enricher (own internal TXs)
	musicPath    string
	filmsPath    string
	coversDir    string
	artistImgDir string
	lyricsDir    string
	lastfmKey    string
	lastfmSecret string
	video        *usecase.VideoUsecase
	ebook        *usecase.EbookUsecase
	ebooksPath   string
	ebookCoversDir string
	cloakProxyURL  string // routes external image fetches through proxy
}

var hexID = regexp.MustCompile(`^[0-9a-f]{16}$`)

var resizeWhitelist = map[int]bool{80: true, 200: true, 300: true, 400: true, 512: true}

// serveResizedImage serves id+".jpg" from imgDir, optionally resizing to ?w=N.
// Resized copies are cached in imgDir/resized/. Always sets a 7-day Cache-Control.
// singleflight prevents concurrent requests from writing the same resized file simultaneously.
func serveResizedImage(w http.ResponseWriter, r *http.Request, imgDir, id string) {
	filePath := filepath.Join(imgDir, id+".jpg")
	w.Header().Set("Cache-Control", "public, max-age=604800")

	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		log.Printf("serveResizedImage: cover not found: %s", id)
		http.NotFound(w, r)
		return
	}

	width, err := strconv.Atoi(r.URL.Query().Get("w"))
	if err != nil || !resizeWhitelist[width] {
		http.ServeFile(w, r, filePath)
		return
	}

	resizedDir := filepath.Join(imgDir, "resized")
	resizedPath := filepath.Join(resizedDir, fmt.Sprintf("%s_%d.jpg", id, width))

	if _, statErr := os.Stat(resizedPath); statErr == nil {
		http.ServeFile(w, r, resizedPath)
		return
	}

	// singleflight: only one goroutine generates the resized file; concurrent requests wait.
	coverSF.Do(resizedPath, func() (any, error) {
		if _, statErr := os.Stat(resizedPath); statErr == nil {
			return nil, nil // already generated by a concurrent request
		}

		f, openErr := os.Open(filePath)
		if openErr != nil {
			return nil, openErr
		}
		defer f.Close()

		srcImg, decErr := jpeg.Decode(f)
		if decErr != nil {
			return nil, decErr
		}

		bounds := srcImg.Bounds()
		if width >= bounds.Dx() {
			return nil, nil // original is smaller — caller falls back to filePath
		}

		newH := bounds.Dy() * width / bounds.Dx()
		dst := image.NewRGBA(image.Rect(0, 0, width, newH))
		xdraw.BiLinear.Scale(dst, dst.Bounds(), srcImg, bounds, xdraw.Over, nil)

		if mkErr := os.MkdirAll(resizedDir, 0755); mkErr != nil {
			log.Printf("serveResizedImage mkdir %s: %v", resizedDir, mkErr)
			return nil, mkErr
		}

		out, createErr := os.Create(resizedPath)
		if createErr != nil {
			log.Printf("serveResizedImage create %s: %v", resizedPath, createErr)
			return nil, createErr
		}

		if encErr := jpeg.Encode(out, dst, &jpeg.Options{Quality: 75}); encErr != nil {
			out.Close()
			os.Remove(resizedPath)
			log.Printf("serveResizedImage encode %s: %v", resizedPath, encErr)
			return nil, encErr
		}
		out.Close()
		return nil, nil
	})

	if _, statErr := os.Stat(resizedPath); statErr == nil {
		http.ServeFile(w, r, resizedPath)
		return
	}
	http.ServeFile(w, r, filePath)
}

func (h *handlers) health(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "ok", "version": "0.1.0"})
}

func (h *handlers) stats(w http.ResponseWriter, r *http.Request) {
	s, err := h.lib.GetStats(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=60")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(s)
}

// GET /api/stats/plays?days=30 — top-played tracks (local track_plays count +
// lastfm_backfill_count baseline) and a local-only daily play histogram.
// Last.fm's userplaycount has no per-play timestamp, so the daily breakdown
// can only ever reflect plays recorded locally (see llmwiki proposal
// 020826-music-play-stats-chart-be-fe for why this split is intentional).
func (h *handlers) playStats(w http.ResponseWriter, r *http.Request) {
	days := 30
	if n, err := strconv.Atoi(r.URL.Query().Get("days")); err == nil && n > 0 && n <= 365 {
		days = n
	}

	type topTrack struct {
		ID         string `json:"id"`
		Title      string `json:"title"`
		ArtistName string `json:"artist_name"`
		AlbumTitle string `json:"album_title"`
		CoverURL   string `json:"cover_url"`
		Plays      int    `json:"plays"`
	}
	top := []topTrack{}
	rows, err := h.scanDB.QueryContext(r.Context(), `
		SELECT t.id, t.title, ar.name, al.title, COALESCE(al.cover_path,''),
		       t.lastfm_backfill_count + COUNT(tp.id) AS total_plays
		FROM tracks t
		JOIN albums al ON al.id = t.album_id
		JOIN artists ar ON ar.id = al.artist_id
		LEFT JOIN track_plays tp ON tp.track_id = t.id
		GROUP BY t.id, ar.name, al.title, al.cover_path
		HAVING t.lastfm_backfill_count + COUNT(tp.id) > 0
		ORDER BY total_plays DESC LIMIT 10`)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	for rows.Next() {
		var tt topTrack
		if rows.Scan(&tt.ID, &tt.Title, &tt.ArtistName, &tt.AlbumTitle, &tt.CoverURL, &tt.Plays) == nil {
			top = append(top, tt)
		}
	}
	rows.Close()

	type dayCount struct {
		Date  string `json:"date"`
		Plays int    `json:"plays"`
	}
	daily := []dayCount{}
	rows2, err := h.scanDB.QueryContext(r.Context(), `
		SELECT to_char(to_timestamp(played_at), 'YYYY-MM-DD') d, COUNT(*)
		FROM track_plays
		WHERE played_at >= extract(epoch from now() - ($1 || ' days')::interval)
		GROUP BY d ORDER BY d`, days)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	for rows2.Next() {
		var dc dayCount
		if rows2.Scan(&dc.Date, &dc.Plays) == nil {
			daily = append(daily, dc)
		}
	}
	rows2.Close()

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{"top": top, "daily": daily})
}

func (h *handlers) scan(w http.ResponseWriter, r *http.Request) {
	// Scan still uses the library package directly — it has its own internal
	// transaction via UoW (see library/scanner.go refactor).
	scanLibrary(h, w)
}

func (h *handlers) cover(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if strings.HasPrefix(id, "yt:") {
		ytID := id[3:]
		if len(ytID) != 11 {
			http.NotFound(w, r)
			return
		}
		cachePath := filepath.Join(h.coversDir, "yt_"+ytID+".jpg")
		// Evict any previously-cached file that isn't a valid JPEG (e.g. JSON from old cloak-proxy bug).
		if f, ferr := os.Open(cachePath); ferr == nil {
			hdr := make([]byte, 2)
			n, _ := f.Read(hdr)
			f.Close()
			if n < 2 || hdr[0] != 0xFF || hdr[1] != 0xD8 {
				os.Remove(cachePath)
			}
		}
		if _, err := os.Stat(cachePath); os.IsNotExist(err) {
			// singleflight: only one goroutine fetches a given YouTube thumbnail; concurrent requests wait.
			coverSF.Do("yt:"+ytID, func() (any, error) {
				if _, statErr := os.Stat(cachePath); statErr == nil {
					return nil, nil // already fetched by a concurrent request
				}
				urls := []string{
					"https://i.ytimg.com/vi/" + ytID + "/maxresdefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/sddefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/hqdefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/mqdefault.jpg",
				}
				// Always fetch directly — cloak-proxy returns JSON {"html":"..."}, not binary.
				for _, u := range urls {
					ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
					req, _ := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
					resp, fetchErr := http.DefaultClient.Do(req)
					cancel()
					if fetchErr != nil || resp.StatusCode != http.StatusOK {
						if resp != nil { resp.Body.Close() }
						log.Printf("[cover] yt thumbnail %s → %s: %v", ytID, u, fetchErr)
						continue
					}
					data, readErr := io.ReadAll(resp.Body)
					resp.Body.Close()
					if readErr != nil || len(data) < 2 || data[0] != 0xFF || data[1] != 0xD8 {
						// not a valid JPEG — skip this URL
						log.Printf("[cover] yt thumbnail %s → %s: invalid JPEG (len=%d)", ytID, u, len(data))
						continue
					}
					if writeErr := os.WriteFile(cachePath, data, 0644); writeErr != nil {
						os.Remove(cachePath)
					}
					break
				}
				return nil, nil
			})
		}
		if _, err := os.Stat(cachePath); os.IsNotExist(err) {
			// Thumbnail unavailable — return 503 so client onerror fires and can retry.
			w.Header().Set("Cache-Control", "no-store")
			http.Error(w, "thumbnail unavailable", http.StatusServiceUnavailable)
			return
		}
		w.Header().Set("Cache-Control", "public, max-age=604800")
		http.ServeFile(w, r, cachePath)
		return
	}
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	serveResizedImage(w, r, h.coversDir, id)
}

func (h *handlers) artistImage(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	serveResizedImage(w, r, h.artistImgDir, id)
}

func (h *handlers) artistDetail(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	detail, err := h.lib.ArtistDetail(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if detail == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(detail)
}

func (h *handlers) listArtists(w http.ResponseWriter, r *http.Request) {
	artists, err := h.lib.ListArtists(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(artists)
}

func (h *handlers) listAlbums(w http.ResponseWriter, r *http.Request) {
	artistID := r.URL.Query().Get("artist_id")
	albums, err := h.lib.ListAlbums(r.Context(), artistID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(albums)
}

func (h *handlers) getAlbum(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	album, err := h.lib.GetAlbum(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if album == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(album)
}

func (h *handlers) listTracks(w http.ResponseWriter, r *http.Request) {
	albumID := r.URL.Query().Get("album_id")
	tracks, err := h.lib.ListTracks(r.Context(), albumID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(tracks)
}

// flushWriter flushes after every Write so a live ffmpeg transcode reaches
// the client progressively instead of waiting on Go's response buffering
// (nginx already runs proxy_buffering off for this path — see CozyArchitecture.md).
type flushWriter struct{ w http.ResponseWriter }

func (fw flushWriter) Write(p []byte) (int, error) {
	n, err := fw.w.Write(p)
	if f, ok := fw.w.(http.Flusher); ok {
		f.Flush()
	}
	return n, err
}

func (h *handlers) stream(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	filePath, err := h.lib.TrackFilePath(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if filePath == "" {
		http.NotFound(w, r)
		return
	}

	// Correlation IDs from the frontend (see PlayerContext.tsx streamUrl) — used
	// only in plain log lines below so retries of the same playback attempt can
	// be grouped when reading logs. Never pass these into a Prometheus label:
	// they are near-random per attempt, and would create an unbounded number of
	// distinct time series.
	clientID := r.URL.Query().Get("client_id")
	attemptID := r.URL.Query().Get("attempt_id")

	// ?q=320 → transcode to 320 kbps MP3 via ffmpeg (all formats, not just lossless —
	// ensures browsers get valid MP3 even for unusual/corrupt MP3 encodings).
	// Cached to disk after first transcode: replays and gapless preloads of the
	// same track then serve as a plain Range-seekable file instead of re-running
	// ffmpeg every time (see llmwiki postmortem on mobile stutter, 2026-07-12).
	if r.URL.Query().Get("q") == "320" {
		if cachedPath, ok := transcode.Cached(id, "320", "mp3"); ok {
			w.Header().Set("X-Quality", "320kbps-mp3")
			w.Header().Set("X-Cache", "hit")
			http.ServeFile(w, r, cachedPath)
			return
		}
		w.Header().Set("Content-Type", "audio/mpeg")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("X-Accel-Buffering", "no")
		w.Header().Set("X-Quality", "320kbps-mp3")
		w.Header().Set("X-Cache", "miss")
		metrics.StreamsTotal.WithLabelValues("320kbps").Inc()
		fw := flushWriter{w}
		if err := transcode.EncodeAndCache(r.Context(), fw, id, "320", "mp3", func(ctx context.Context, out io.Writer) error {
			return transcode.ToMP3_320(ctx, filePath, out)
		}); err != nil {
			log.Printf("transcode %s: %v (client=%s attempt=%s)", id, err, clientID, attemptID)
			metrics.StreamErrorsTotal.WithLabelValues("320kbps", "transcode_failed").Inc()
		}
		return
	}

	// ?q=lossless-clean → copy lossless audio but strip metadata on-the-fly to bypass corrupt tags crashing browser demuxers
	if r.URL.Query().Get("q") == "lossless-clean" && transcode.IsLossless(filePath) {
		if cachedPath, ok := transcode.Cached(id, "lossless-clean", "flac"); ok {
			w.Header().Set("X-Quality", "lossless-clean")
			w.Header().Set("X-Cache", "hit")
			http.ServeFile(w, r, cachedPath)
			return
		}
		w.Header().Set("Content-Type", "audio/flac")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("X-Accel-Buffering", "no")
		w.Header().Set("X-Quality", "lossless-clean")
		w.Header().Set("X-Cache", "miss")
		metrics.StreamsTotal.WithLabelValues("lossless-clean").Inc()
		fw := flushWriter{w}
		if err := transcode.EncodeAndCache(r.Context(), fw, id, "lossless-clean", "flac", func(ctx context.Context, out io.Writer) error {
			return transcode.ToCleanFLAC(ctx, filePath, out)
		}); err != nil {
			log.Printf("clean flac %s: %v (client=%s attempt=%s)", id, err, clientID, attemptID)
			metrics.StreamErrorsTotal.WithLabelValues("lossless-clean", "transcode_failed").Inc()
		}
		return
	}

	// Default: serve file with Range support (lossless passthrough)
	// Cache-Control: public lets CF edge cache the file after first play —
	// subsequent plays are served from CF datacenter near the user, not tunneled home.
	metrics.StreamsTotal.WithLabelValues("lossless").Inc()
	w.Header().Set("X-Quality", "lossless")
	w.Header().Set("Cache-Control", "public, max-age=3600")
	http.ServeFile(w, r, filePath)
}

func (h *handlers) smartQueue(w http.ResponseWriter, r *http.Request) {
	trackID := r.URL.Query().Get("track_id")
	if !hexID.MatchString(trackID) {
		http.Error(w, "invalid track_id", http.StatusBadRequest)
		return
	}
	metrics.SmartQueueTotal.Inc()
	limit := 30
	if n, err := strconv.Atoi(r.URL.Query().Get("limit")); err == nil && n > 0 && n <= 100 {
		limit = n
	}

	tracks, err := h.lib.SmartQueue(r.Context(), trackID, limit)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if tracks == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(tracks)
}

// POST /api/tracks/{id}/play — fire-and-forget play-count log. Never surfaces
// a hard error to the player UI; a failed write here must not interrupt
// playback, so we just log server-side and always return 204.
func (h *handlers) recordPlay(w http.ResponseWriter, r *http.Request) {
	trackID := r.PathValue("id")
	if !hexID.MatchString(trackID) {
		http.Error(w, "invalid track id", http.StatusBadRequest)
		return
	}
	if err := h.lib.RecordPlay(r.Context(), trackID); err != nil {
		log.Printf("recordPlay %s: %v", trackID, err)
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *handlers) search(w http.ResponseWriter, r *http.Request) {
	q := strings.TrimSpace(r.URL.Query().Get("q"))
	if len(q) >= 2 {
		metrics.SearchesTotal.Inc()
	}
	if len(q) < 2 {
		w.Header().Set("Cache-Control", "public, max-age=30")
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]any{
			"artists": []any{}, "albums": []any{}, "tracks": []any{},
		})
		return
	}

	result, err := h.lib.SearchAll(r.Context(), q)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=30")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}
