package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"image"
	"image/jpeg"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"cozyroom/internal/metrics"
	"cozyroom/internal/transcode"
	"cozyroom/internal/usecase"
	xdraw "golang.org/x/image/draw"
	"golang.org/x/sync/singleflight"
)

var coverSF singleflight.Group

type handlers struct {
	lib          *usecase.LibraryUsecase
	lyrics       *usecase.LyricsUsecase
	settings     *usecase.SettingsUsecase
	playback     *usecase.PlaybackUsecase
	scanDB       *sql.DB // only for scanner/enricher (own internal TXs)
	musicPath    string
	filmsPath    string
	coversDir    string
	artistImgDir string
	lyricsDir    string
	lastfmKey    string
	lastfmSecret string
	video        *usecase.VideoUsecase
	ebook        *usecase.EbookUsecase
	ebooksPath   string
	ebookCoversDir string
	cloakProxyURL  string // routes external image fetches through proxy
}

var hexID = regexp.MustCompile(`^[0-9a-f]{16}$`)

var resizeWhitelist = map[int]bool{80: true, 200: true, 300: true, 400: true, 512: true}

// serveResizedImage serves id+".jpg" from imgDir, optionally resizing to ?w=N.
// Resized copies are cached in imgDir/resized/. Always sets a 7-day Cache-Control.
// singleflight prevents concurrent requests from writing the same resized file simultaneously.
func serveCoverPlaceholder(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "image/svg+xml")
	w.Header().Set("Cache-Control", "public, max-age=3600")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><rect width="1" height="1" fill="#1e1e2e"/></svg>`))
}

func serveResizedImage(w http.ResponseWriter, r *http.Request, imgDir, id string) {
	filePath := filepath.Join(imgDir, id+".jpg")
	w.Header().Set("Cache-Control", "public, max-age=604800")

	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		serveCoverPlaceholder(w)
		return
	}

	width, err := strconv.Atoi(r.URL.Query().Get("w"))
	if err != nil || !resizeWhitelist[width] {
		http.ServeFile(w, r, filePath)
		return
	}

	resizedDir := filepath.Join(imgDir, "resized")
	resizedPath := filepath.Join(resizedDir, fmt.Sprintf("%s_%d.jpg", id, width))

	if _, statErr := os.Stat(resizedPath); statErr == nil {
		http.ServeFile(w, r, resizedPath)
		return
	}

	// singleflight: only one goroutine generates the resized file; concurrent requests wait.
	coverSF.Do(resizedPath, func() (any, error) {
		if _, statErr := os.Stat(resizedPath); statErr == nil {
			return nil, nil // already generated by a concurrent request
		}

		f, openErr := os.Open(filePath)
		if openErr != nil {
			return nil, openErr
		}
		defer f.Close()

		srcImg, decErr := jpeg.Decode(f)
		if decErr != nil {
			return nil, decErr
		}

		bounds := srcImg.Bounds()
		if width >= bounds.Dx() {
			return nil, nil // original is smaller — caller falls back to filePath
		}

		newH := bounds.Dy() * width / bounds.Dx()
		dst := image.NewRGBA(image.Rect(0, 0, width, newH))
		xdraw.BiLinear.Scale(dst, dst.Bounds(), srcImg, bounds, xdraw.Over, nil)

		if mkErr := os.MkdirAll(resizedDir, 0755); mkErr != nil {
			log.Printf("serveResizedImage mkdir %s: %v", resizedDir, mkErr)
			return nil, mkErr
		}

		out, createErr := os.Create(resizedPath)
		if createErr != nil {
			log.Printf("serveResizedImage create %s: %v", resizedPath, createErr)
			return nil, createErr
		}

		if encErr := jpeg.Encode(out, dst, &jpeg.Options{Quality: 75}); encErr != nil {
			out.Close()
			os.Remove(resizedPath)
			log.Printf("serveResizedImage encode %s: %v", resizedPath, encErr)
			return nil, encErr
		}
		out.Close()
		return nil, nil
	})

	if _, statErr := os.Stat(resizedPath); statErr == nil {
		http.ServeFile(w, r, resizedPath)
		return
	}
	http.ServeFile(w, r, filePath)
}

func (h *handlers) health(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "ok", "version": "0.1.0"})
}

func (h *handlers) stats(w http.ResponseWriter, r *http.Request) {
	s, err := h.lib.GetStats(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=60")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(s)
}

func (h *handlers) scan(w http.ResponseWriter, r *http.Request) {
	// Scan still uses the library package directly — it has its own internal
	// transaction via UoW (see library/scanner.go refactor).
	scanLibrary(h, w)
}

func (h *handlers) cover(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if strings.HasPrefix(id, "yt:") {
		ytID := id[3:]
		if len(ytID) != 11 {
			http.NotFound(w, r)
			return
		}
		cachePath := filepath.Join(h.coversDir, "yt_"+ytID+".jpg")
		// Evict any previously-cached file that isn't a valid JPEG (e.g. JSON from old cloak-proxy bug).
		if f, ferr := os.Open(cachePath); ferr == nil {
			hdr := make([]byte, 2)
			n, _ := f.Read(hdr)
			f.Close()
			if n < 2 || hdr[0] != 0xFF || hdr[1] != 0xD8 {
				os.Remove(cachePath)
			}
		}
		if _, err := os.Stat(cachePath); os.IsNotExist(err) {
			// singleflight: only one goroutine fetches a given YouTube thumbnail; concurrent requests wait.
			coverSF.Do("yt:"+ytID, func() (any, error) {
				if _, statErr := os.Stat(cachePath); statErr == nil {
					return nil, nil // already fetched by a concurrent request
				}
				urls := []string{
					"https://i.ytimg.com/vi/" + ytID + "/maxresdefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/sddefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/hqdefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/mqdefault.jpg",
				}
				// Always fetch directly — cloak-proxy returns JSON {"html":"..."}, not binary.
				for _, u := range urls {
					ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
					req, _ := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
					resp, fetchErr := http.DefaultClient.Do(req)
					cancel()
					if fetchErr != nil || resp.StatusCode != http.StatusOK {
						if resp != nil { resp.Body.Close() }
						log.Printf("[cover] yt thumbnail %s → %s: %v", ytID, u, fetchErr)
						continue
					}
					data, readErr := io.ReadAll(resp.Body)
					resp.Body.Close()
					if readErr != nil || len(data) < 2 || data[0] != 0xFF || data[1] != 0xD8 {
						// not a valid JPEG — skip this URL
						log.Printf("[cover] yt thumbnail %s → %s: invalid JPEG (len=%d)", ytID, u, len(data))
						continue
					}
					if writeErr := os.WriteFile(cachePath, data, 0644); writeErr != nil {
						os.Remove(cachePath)
					}
					break
				}
				return nil, nil
			})
		}
		if _, err := os.Stat(cachePath); os.IsNotExist(err) {
			// Thumbnail unavailable — return 503 so client onerror fires and can retry.
			w.Header().Set("Cache-Control", "no-store")
			http.Error(w, "thumbnail unavailable", http.StatusServiceUnavailable)
			return
		}
		w.Header().Set("Cache-Control", "public, max-age=604800")
		http.ServeFile(w, r, cachePath)
		return
	}
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	serveResizedImage(w, r, h.coversDir, id)
}

func (h *handlers) artistImage(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	serveResizedImage(w, r, h.artistImgDir, id)
}

func (h *handlers) artistDetail(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	detail, err := h.lib.ArtistDetail(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if detail == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(detail)
}

func (h *handlers) listArtists(w http.ResponseWriter, r *http.Request) {
	artists, err := h.lib.ListArtists(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(artists)
}

func (h *handlers) listAlbums(w http.ResponseWriter, r *http.Request) {
	artistID := r.URL.Query().Get("artist_id")
	albums, err := h.lib.ListAlbums(r.Context(), artistID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(albums)
}

func (h *handlers) getAlbum(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	album, err := h.lib.GetAlbum(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if album == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(album)
}

func (h *handlers) listTracks(w http.ResponseWriter, r *http.Request) {
	albumID := r.URL.Query().Get("album_id")
	tracks, err := h.lib.ListTracks(r.Context(), albumID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(tracks)
}

func (h *handlers) stream(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	filePath, err := h.lib.TrackFilePath(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if filePath == "" {
		http.NotFound(w, r)
		return
	}

	// ?q=320 → transcode to 320 kbps MP3 via ffmpeg (all formats, not just lossless —
	// ensures browsers get valid MP3 even for unusual/corrupt MP3 encodings)
	if r.URL.Query().Get("q") == "320" {
		w.Header().Set("Content-Type", "audio/mpeg")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("X-Accel-Buffering", "no")
		w.Header().Set("X-Quality", "320kbps-mp3")
		metrics.StreamsTotal.WithLabelValues("320kbps").Inc()
		if err := transcode.ToMP3_320(r.Context(), filePath, w); err != nil {
			log.Printf("transcode %s: %v", id, err)
			metrics.StreamErrorsTotal.WithLabelValues("320kbps", "transcode_failed").Inc()
		}
		return
	}

	// ?q=lossless-clean → copy lossless audio but strip metadata on-the-fly to bypass corrupt tags crashing browser demuxers
	if r.URL.Query().Get("q") == "lossless-clean" && transcode.IsLossless(filePath) {
		w.Header().Set("Content-Type", "audio/flac")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("X-Accel-Buffering", "no")
		w.Header().Set("X-Quality", "lossless-clean")
		metrics.StreamsTotal.WithLabelValues("lossless-clean").Inc()
		if err := transcode.ToCleanFLAC(r.Context(), filePath, w); err != nil {
			log.Printf("clean flac %s: %v", id, err)
			metrics.StreamErrorsTotal.WithLabelValues("lossless-clean", "transcode_failed").Inc()
		}
		return
	}

	// Default: serve file with Range support (lossless passthrough)
	// Cache-Control: public lets CF edge cache the file after first play —
	// subsequent plays are served from CF datacenter near the user, not tunneled home.
	metrics.StreamsTotal.WithLabelValues("lossless").Inc()
	w.Header().Set("X-Quality", "lossless")
	w.Header().Set("Cache-Control", "public, max-age=3600")
	http.ServeFile(w, r, filePath)
}

func (h *handlers) smartQueue(w http.ResponseWriter, r *http.Request) {
	trackID := r.URL.Query().Get("track_id")
	if !hexID.MatchString(trackID) {
		http.Error(w, "invalid track_id", http.StatusBadRequest)
		return
	}
	metrics.SmartQueueTotal.Inc()
	limit := 30
	if n, err := strconv.Atoi(r.URL.Query().Get("limit")); err == nil && n > 0 && n <= 100 {
		limit = n
	}

	tracks, err := h.lib.SmartQueue(r.Context(), trackID, limit)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if tracks == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(tracks)
}

func (h *handlers) search(w http.ResponseWriter, r *http.Request) {
	q := strings.TrimSpace(r.URL.Query().Get("q"))
	if len(q) >= 2 {
		metrics.SearchesTotal.Inc()
	}
	if len(q) < 2 {
		w.Header().Set("Cache-Control", "public, max-age=30")
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]any{
			"artists": []any{}, "albums": []any{}, "tracks": []any{},
		})
		return
	}

	result, err := h.lib.SearchAll(r.Context(), q)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Cache-Control", "public, max-age=30")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}
