package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"image"
	"image/jpeg"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"cozyroom/internal/metrics"
	"cozyroom/internal/transcode"
	"cozyroom/internal/usecase"
	xdraw "golang.org/x/image/draw"
	"golang.org/x/sync/singleflight"
)

var coverSF singleflight.Group

type handlers struct {
	lib          *usecase.LibraryUsecase
	lyrics       *usecase.LyricsUsecase
	settings     *usecase.SettingsUsecase
	playback     *usecase.PlaybackUsecase
	scanDB       *sql.DB // only for scanner/enricher (own internal TXs)
	musicPath    string
	filmsPath    string
	coversDir    string
	artistImgDir string
	lyricsDir    string
	lastfmKey    string
	lastfmSecret string
	video        *usecase.VideoUsecase
	ebook        *usecase.EbookUsecase
	ebooksPath   string
	ebookCoversDir string
	cloakProxyURL  string // routes external image fetches through proxy
}

var hexID = regexp.MustCompile(`^[0-9a-f]{16}$`)

var resizeWhitelist = map[int]bool{80: true, 200: true, 300: true, 400: true, 512: true}

// serveResizedImage serves id+".jpg" from imgDir, optionally resizing to ?w=N.
// Resized copies are cached in imgDir/resized/. Always sets a 7-day Cache-Control.
// singleflight prevents concurrent requests from writing the same resized file simultaneously.
func serveResizedImage(w http.ResponseWriter, r *http.Request, imgDir, id string) {
	filePath := filepath.Join(imgDir, id+".jpg")
	w.Header().Set("Cache-Control", "public, max-age=604800")

	width, err := strconv.Atoi(r.URL.Query().Get("w"))
	if err != nil || !resizeWhitelist[width] {
		http.ServeFile(w, r, filePath)
		return
	}

	resizedDir := filepath.Join(imgDir, "resized")
	resizedPath := filepath.Join(resizedDir, fmt.Sprintf("%s_%d.jpg", id, width))

	if _, statErr := os.Stat(resizedPath); statErr == nil {
		http.ServeFile(w, r, resizedPath)
		return
	}

	// singleflight: only one goroutine generates the resized file; concurrent requests wait.
	coverSF.Do(resizedPath, func() (any, error) {
		if _, statErr := os.Stat(resizedPath); statErr == nil {
			return nil, nil // already generated by a concurrent request
		}

		f, openErr := os.Open(filePath)
		if openErr != nil {
			return nil, openErr
		}
		defer f.Close()

		srcImg, decErr := jpeg.Decode(f)
		if decErr != nil {
			return nil, decErr
		}

		bounds := srcImg.Bounds()
		if width >= bounds.Dx() {
			return nil, nil // original is smaller — caller falls back to filePath
		}

		newH := bounds.Dy() * width / bounds.Dx()
		dst := image.NewRGBA(image.Rect(0, 0, width, newH))
		xdraw.BiLinear.Scale(dst, dst.Bounds(), srcImg, bounds, xdraw.Over, nil)

		if mkErr := os.MkdirAll(resizedDir, 0755); mkErr != nil {
			log.Printf("serveResizedImage mkdir %s: %v", resizedDir, mkErr)
			return nil, mkErr
		}

		out, createErr := os.Create(resizedPath)
		if createErr != nil {
			log.Printf("serveResizedImage create %s: %v", resizedPath, createErr)
			return nil, createErr
		}

		if encErr := jpeg.Encode(out, dst, &jpeg.Options{Quality: 75}); encErr != nil {
			out.Close()
			os.Remove(resizedPath)
			log.Printf("serveResizedImage encode %s: %v", resizedPath, encErr)
			return nil, encErr
		}
		out.Close()
		return nil, nil
	})

	if _, statErr := os.Stat(resizedPath); statErr == nil {
		http.ServeFile(w, r, resizedPath)
		return
	}
	http.ServeFile(w, r, filePath)
}

func (h *handlers) health(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "ok", "version": "0.1.0"})
}

func (h *handlers) stats(w http.ResponseWriter, r *http.Request) {
	s, err := h.lib.GetStats(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(s)
}

func (h *handlers) scan(w http.ResponseWriter, r *http.Request) {
	// Scan still uses the library package directly — it has its own internal
	// transaction via UoW (see library/scanner.go refactor).
	scanLibrary(h, w)
}

func (h *handlers) cover(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if strings.HasPrefix(id, "yt:") {
		ytID := id[3:]
		if len(ytID) != 11 {
			http.NotFound(w, r)
			return
		}
		cachePath := filepath.Join(h.coversDir, "yt_"+ytID+".jpg")
		if _, err := os.Stat(cachePath); os.IsNotExist(err) {
			// singleflight: only one goroutine fetches a given YouTube thumbnail; concurrent requests wait.
			coverSF.Do("yt:"+ytID, func() (any, error) {
				if _, statErr := os.Stat(cachePath); statErr == nil {
					return nil, nil // already fetched by a concurrent request
				}
				urls := []string{
					"https://i.ytimg.com/vi/" + ytID + "/maxresdefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/sddefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/hqdefault.jpg",
					"https://i.ytimg.com/vi/" + ytID + "/mqdefault.jpg",
				}
				for _, u := range urls {
					var (resp *http.Response; fetchErr error)
					ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
					if h.cloakProxyURL != "" {
						req, _ := http.NewRequestWithContext(ctx, http.MethodPost,
							h.cloakProxyURL+"/fetch",
							strings.NewReader(`{"url":"`+u+`"}`))
						req.Header.Set("Content-Type", "application/json")
						resp, fetchErr = http.DefaultClient.Do(req)
					} else {
						req, _ := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
						resp, fetchErr = http.DefaultClient.Do(req)
					}
					cancel()
					if fetchErr != nil || resp.StatusCode != http.StatusOK {
						if resp != nil { resp.Body.Close() }
						log.Printf("[cover] yt thumbnail %s → %s: %v", ytID, u, fetchErr)
						continue
					}
					f, err := os.Create(cachePath)
					if err != nil {
						resp.Body.Close()
						break
					}
					_, copyErr := io.Copy(f, resp.Body)
					f.Close()
					resp.Body.Close()
					if copyErr != nil {
						os.Remove(cachePath)
					}
					break
				}
				return nil, nil
			})
		}
		if _, err := os.Stat(cachePath); os.IsNotExist(err) {
			// All fetches failed — return a transparent 1×1 placeholder to avoid broken-image icons.
			w.Header().Set("Content-Type", "image/jpeg")
			w.Header().Set("Cache-Control", "no-cache")
			w.WriteHeader(http.StatusOK)
			w.Write([]byte{
				0xff,0xd8,0xff,0xe0,0,0x10,0x4a,0x46,0x49,0x46,0,1,1,0,0,1,0,1,0,0,
				0xff,0xdb,0,0x43,0,8,6,6,7,6,5,8,7,7,7,9,9,8,0xa,0xc,0x14,0xd,0xc,
				0xb,0xb,0xc,0x19,0x12,0x13,0xf,0x14,0x1d,0x1a,0x1f,0x1e,0x1d,0x1a,
				0x1c,0x1c,0x20,0x24,0x2e,0x27,0x20,0x22,0x2c,0x23,0x1c,0x1c,0x28,
				0x37,0x29,0x2c,0x30,0x31,0x34,0x34,0x34,0x1f,0x27,0x39,0x3d,0x38,
				0x32,0x3c,0x2e,0x33,0x34,0x32,0xff,0xc0,0,0xb,8,0,1,0,1,1,1,0x11,0,
				0xff,0xc4,0,0x1f,0,0,1,5,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,2,3,4,5,6,7,
				8,9,0xa,0xb,0xff,0xc4,0,0xb5,0x10,0,2,1,3,3,2,4,3,5,5,4,4,0,0,1,
				0x7d,1,2,3,0,4,0x11,5,0x12,0x21,0x31,0x41,6,0x13,0x51,0x61,7,0x22,
				0x71,0x14,0x32,0x81,0x91,0xa1,8,0x23,0x42,0xb1,0xc1,0x15,0x52,0xd1,
				0xf0,0x24,0x33,0x62,0x72,0x82,9,0x0a,0x16,0x17,0x18,0x19,0x1a,0x25,
				0x26,0x27,0x28,0x29,0x2a,0x34,0x35,0x36,0x37,0x38,0x39,0x3a,0x43,
				0x44,0x45,0x46,0x47,0x48,0x49,0x4a,0x53,0x54,0x55,0x56,0x57,0x58,
				0x59,0x5a,0x63,0x64,0x65,0x66,0x67,0x68,0x69,0x6a,0x73,0x74,0x75,
				0x76,0x77,0x78,0x79,0x7a,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,
				0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9a,0xa2,0xa3,0xa4,0xa5,
				0xa6,0xa7,0xa8,0xa9,0xaa,0xb2,0xb3,0xb4,0xb5,0xb6,0xb7,0xb8,0xb9,
				0xba,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7,0xc8,0xc9,0xca,0xd2,0xd3,0xd4,
				0xd5,0xd6,0xd7,0xd8,0xd9,0xda,0xe1,0xe2,0xe3,0xe4,0xe5,0xe6,0xe7,
				0xe8,0xe9,0xea,0xf1,0xf2,0xf3,0xf4,0xf5,0xf6,0xf7,0xf8,0xf9,0xfa,
				0xff,0xda,0,8,1,1,0,0,0x3f,0,0xfb,0x34,0xff,0xd9,
			})
			return
		}
		w.Header().Set("Cache-Control", "public, max-age=604800")
		http.ServeFile(w, r, cachePath)
		return
	}
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	serveResizedImage(w, r, h.coversDir, id)
}

func (h *handlers) artistImage(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	serveResizedImage(w, r, h.artistImgDir, id)
}

func (h *handlers) artistDetail(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if !hexID.MatchString(id) {
		http.NotFound(w, r)
		return
	}
	detail, err := h.lib.ArtistDetail(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if detail == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(detail)
}

func (h *handlers) listArtists(w http.ResponseWriter, r *http.Request) {
	artists, err := h.lib.ListArtists(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(artists)
}

func (h *handlers) listAlbums(w http.ResponseWriter, r *http.Request) {
	artistID := r.URL.Query().Get("artist_id")
	albums, err := h.lib.ListAlbums(r.Context(), artistID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(albums)
}

func (h *handlers) listTracks(w http.ResponseWriter, r *http.Request) {
	albumID := r.URL.Query().Get("album_id")
	tracks, err := h.lib.ListTracks(r.Context(), albumID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(tracks)
}

func (h *handlers) stream(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	filePath, err := h.lib.TrackFilePath(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if filePath == "" {
		http.NotFound(w, r)
		return
	}

	// ?q=320 → transcode lossless to 320 kbps MP3 on the fly via ffmpeg
	if r.URL.Query().Get("q") == "320" && transcode.IsLossless(filePath) {
		w.Header().Set("Content-Type", "audio/mpeg")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("X-Accel-Buffering", "no")
		w.Header().Set("X-Quality", "320kbps-mp3")
		metrics.StreamsTotal.WithLabelValues("320kbps").Inc()
		if err := transcode.ToMP3_320(r.Context(), filePath, w); err != nil {
			log.Printf("transcode %s: %v", id, err)
			metrics.StreamErrorsTotal.WithLabelValues("320kbps", "transcode_failed").Inc()
		}
		return
	}

	// ?q=lossless-clean → copy lossless audio but strip metadata on-the-fly to bypass corrupt tags crashing browser demuxers
	if r.URL.Query().Get("q") == "lossless-clean" && transcode.IsLossless(filePath) {
		w.Header().Set("Content-Type", "audio/flac")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("X-Accel-Buffering", "no")
		w.Header().Set("X-Quality", "lossless-clean")
		metrics.StreamsTotal.WithLabelValues("lossless-clean").Inc()
		if err := transcode.ToCleanFLAC(r.Context(), filePath, w); err != nil {
			log.Printf("clean flac %s: %v", id, err)
			metrics.StreamErrorsTotal.WithLabelValues("lossless-clean", "transcode_failed").Inc()
		}
		return
	}

	// Default: serve file with Range support (lossless passthrough)
	metrics.StreamsTotal.WithLabelValues("lossless").Inc()
	w.Header().Set("X-Quality", "lossless")
	http.ServeFile(w, r, filePath)
}

func (h *handlers) smartQueue(w http.ResponseWriter, r *http.Request) {
	trackID := r.URL.Query().Get("track_id")
	if !hexID.MatchString(trackID) {
		http.Error(w, "invalid track_id", http.StatusBadRequest)
		return
	}
	metrics.SmartQueueTotal.Inc()
	limit := 30
	if n, err := strconv.Atoi(r.URL.Query().Get("limit")); err == nil && n > 0 && n <= 100 {
		limit = n
	}

	tracks, err := h.lib.SmartQueue(r.Context(), trackID, limit)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if tracks == nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(tracks)
}

func (h *handlers) search(w http.ResponseWriter, r *http.Request) {
	q := strings.TrimSpace(r.URL.Query().Get("q"))
	if len(q) >= 2 {
		metrics.SearchesTotal.Inc()
	}
	if len(q) < 2 {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]any{
			"artists": []any{}, "albums": []any{}, "tracks": []any{},
		})
		return
	}

	result, err := h.lib.SearchAll(r.Context(), q)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}
