#!/usr/bin/env python3
"""
index-frontend.py — scan frontend/src/**/*.tsx|ts, extract component metadata,
write llmwiki/wiki/concepts/frontend-component-map.md

Usage:
    python3 harness/scripts/index-frontend.py [--root <repo-root>]
"""
import re
import sys
import argparse
from pathlib import Path
from datetime import datetime

# ── Regex patterns ────────────────────────────────────────────────────────────
RE_DEFAULT_EXPORT = re.compile(
    r'export\s+default\s+(?:function|class|const)?\s*(\w+)'
)
RE_NAMED_EXPORT = re.compile(
    r'export\s+(?:const|function|class|type|interface|enum)\s+(\w+)'
)
RE_REEXPORT = re.compile(r'export\s*\{([^}]+)\}')
RE_LOCAL_IMPORT = re.compile(
    r"import\s+(?:type\s+)?(?:\{[^}]*\}|[\w*]+(?:\s*,\s*\{[^}]*\})?)\s+from\s+['\"](\.[^'\"]+)['\"]"
)
RE_IMPORT_NAMES = re.compile(
    r"import\s+(?:type\s+)?(?:\{([^}]*)\}|(\w+)(?:\s*,\s*\{([^}]*)\})?)\s+from"
)
RE_PROPS_INTERFACE = re.compile(
    r'(?:interface|type)\s+(\w*[Pp]rops\w*)\s*(?:=\s*\{|[{<])'
)
RE_PROP_FIELD = re.compile(r'^\s{2}(\w+)\??\s*:\s*([^\n;]+)', re.MULTILINE)


def extract_props_block(src: str, props_name: str) -> list[str]:
    """Pull fields from the first matching Props interface/type block."""
    # Find the block starting after the Props declaration
    pattern = re.compile(
        r'(?:interface|type)\s+' + re.escape(props_name) + r'\s*(?:=\s*)?\{([^}]{0,800})\}',
        re.DOTALL
    )
    m = pattern.search(src)
    if not m:
        return []
    block = m.group(1)
    fields = []
    for fm in RE_PROP_FIELD.finditer(block):
        name, typ = fm.group(1), fm.group(2).strip().rstrip(',')
        fields.append(f"{name}: {typ}")
    return fields[:12]  # cap at 12 to keep map readable


def parse_file(path: Path, root: Path) -> dict:
    src = path.read_text(encoding='utf-8', errors='ignore')
    rel = path.relative_to(root).as_posix()

    # Default export
    default_exp = None
    m = RE_DEFAULT_EXPORT.search(src)
    if m:
        default_exp = m.group(1)
    # Also catch: export default ComponentName (no keyword after default)
    if not default_exp:
        m2 = re.search(r'export\s+default\s+(\w+)', src)
        if m2:
            default_exp = m2.group(1)

    # Named exports (deduplicated)
    named = list(dict.fromkeys(RE_NAMED_EXPORT.findall(src)))
    for rx in RE_REEXPORT.finditer(src):
        for name in rx.group(1).split(','):
            n = name.strip().split(' as ')[0].strip()
            if n and n not in named:
                named.append(n)

    # Local imports → resolve relative paths (normalize .. with .resolve())
    local_imports = []
    for m in RE_LOCAL_IMPORT.finditer(src):
        raw = m.group(1)
        base = (path.parent / raw).resolve()  # flatten ../
        resolved = None
        for ext in ['', '.tsx', '.ts', '.jsx', '.js']:
            candidate = Path(str(base) + ext)
            try:
                rel_cand = candidate.relative_to(root).as_posix()
                resolved = rel_cand
                break
            except ValueError:
                pass
        local_imports.append(resolved or raw)
    local_imports = list(dict.fromkeys(local_imports))  # dedup same-module imports

    # Props
    props_matches = RE_PROPS_INTERFACE.findall(src)
    props_info = {}
    for pname in props_matches:
        fields = extract_props_block(src, pname)
        if fields:
            props_info[pname] = fields

    return {
        'path': rel,
        'default_export': default_exp,
        'named_exports': named,
        'local_imports': local_imports,
        'props': props_info,
    }


def build_used_by(files: list[dict]) -> dict[str, list[str]]:
    """Invert the local_imports graph: for each file, who imports it."""
    used_by: dict[str, list[str]] = {f['path']: [] for f in files}
    for f in files:
        for imp in f['local_imports']:
            # Normalise: strip extension
            imp_base = re.sub(r'\.(tsx?|jsx?)$', '', imp)
            for target in used_by:
                target_base = re.sub(r'\.(tsx?|jsx?)$', '', target)
                if imp_base == target_base or imp == target:
                    if f['path'] not in used_by[target]:
                        used_by[target].append(f['path'])
    return used_by


def category(path: str) -> str:
    if '/pages/' in path:
        return 'page'
    if '/components/' in path:
        return 'component'
    if 'Context' in path:
        return 'context'
    if path.endswith('api.ts'):
        return 'api'
    if '/hooks/' in path:
        return 'hook'
    return 'util'


def render_md(files: list[dict], used_by: dict, generated_at: str) -> str:
    lines = [
        '# frontend-component-map',
        '',
        f'> Auto-generated by `harness/scripts/index-frontend.py` on {generated_at}.',
        '> Re-run before any refactor to get a fresh map.',
        '',
        f'**Total files indexed:** {len(files)}',
        '',
        '---',
        '',
    ]

    # Group by category
    categories = ['page', 'component', 'context', 'api', 'hook', 'util']
    cat_titles = {
        'page': '## Pages',
        'component': '## Components',
        'context': '## Contexts',
        'api': '## API / Data',
        'hook': '## Hooks',
        'util': '## Utilities',
    }
    groups: dict[str, list] = {c: [] for c in categories}
    for f in files:
        groups[category(f['path'])].append(f)

    for cat in categories:
        items = groups[cat]
        if not items:
            continue
        lines.append(cat_titles[cat])
        lines.append('')
        for f in sorted(items, key=lambda x: x['path']):
            lines.append(f"### `{f['path']}`")
            if f['default_export']:
                lines.append(f"- **Default export:** `{f['default_export']}`")
            if f['named_exports']:
                lines.append(f"- **Named exports:** {', '.join(f'`{e}`' for e in f['named_exports'][:8])}")
            if f['local_imports']:
                lines.append(f"- **Local imports:** {', '.join(f'`{i}`' for i in f['local_imports'])}")
            ub = used_by.get(f['path'], [])
            if ub:
                lines.append(f"- **Used by:** {', '.join(f'`{u}`' for u in sorted(ub))}")
            else:
                lines.append(f"- **Used by:** _(entry point or unused)_")
            for pname, fields in f['props'].items():
                lines.append(f"- **{pname}:** {', '.join(fields)}")
            lines.append('')

    lines += [
        '---',
        '',
        '## Origin',
        f'- **Generated:** {generated_at}',
        '- **Script:** `harness/scripts/index-frontend.py`',
        '- **Source:** `frontend/src/`',
    ]
    return '\n'.join(lines) + '\n'


HUB_FILES = ['frontend/src/PlayerContext.tsx', 'frontend/src/api.ts', 'frontend/src/types.ts']
HUB_MIN_USED_BY = 3
MIN_FILES = 30


def verify_map(out_path: Path, root: Path) -> bool:
    """Sanity-check the generated map. Returns True if clean, False + prints errors if not."""
    if not out_path.exists():
        print('VERIFY ERROR: map file not found', file=sys.stderr)
        return False

    text = out_path.read_text(encoding='utf-8')
    errors = []

    # Check 1: no unnormalized paths (containing ../)
    bad = re.findall(r'`(frontend/src/[^`]*\.\./[^`]*)`', text)
    if bad:
        errors.append(f'Unnormalized paths ({len(bad)}): {bad[:3]}')

    # Check 2: no duplicate imports on same line
    for line in text.splitlines():
        if 'Local imports:' in line:
            items = re.findall(r'`([^`]+)`', line)
            if len(items) != len(set(items)):
                dupes = [x for x in items if items.count(x) > 1]
                errors.append(f'Duplicate imports: {dupes[0]}')
                break

    # Check 3: hub files have sufficient used-by
    for hub in HUB_FILES:
        block = re.search(
            r'### `' + re.escape(hub) + r'`.*?(?=### |\Z)', text, re.DOTALL
        )
        if block:
            ub = re.search(r'\*\*Used by:\*\* (.*)', block.group())
            if not ub or '_(entry' in ub.group(1):
                errors.append(f'Hub file {hub}: used_by is empty')
            else:
                count = ub.group(1).count('`') // 2
                if count < HUB_MIN_USED_BY:
                    errors.append(f'Hub file {hub}: only {count} used_by (expected ≥{HUB_MIN_USED_BY})')

    # Check 4: minimum file count
    total_match = re.search(r'\*\*Total files indexed:\*\* (\d+)', text)
    if total_match and int(total_match.group(1)) < MIN_FILES:
        errors.append(f'Only {total_match.group(1)} files indexed (expected ≥{MIN_FILES})')

    if errors:
        print('VERIFY FAILED:', file=sys.stderr)
        for e in errors:
            print(f'  ✗ {e}', file=sys.stderr)
        return False

    print(f'Verify OK — {len(HUB_FILES)} hub files checked, no path issues')
    return True


def main():
    parser = argparse.ArgumentParser(description='Index frontend components')
    parser.add_argument('--root', default='.', help='Repo root (default: cwd)')
    parser.add_argument('--src', default='frontend/src',
                        help='Source dir relative to root (default: frontend/src)')
    parser.add_argument('--out', default='llmwiki/wiki/concepts/frontend-component-map.md',
                        help='Output file relative to root')
    parser.add_argument('--verify', action='store_true',
                        help='Only verify existing map (no regeneration), exit 2 on failure')
    args = parser.parse_args()

    root = Path(args.root).resolve()
    out_path = root / args.out

    if args.verify:
        ok = verify_map(out_path, root)
        sys.exit(0 if ok else 2)

    src_dir = root / args.src
    if not src_dir.exists():
        print(f'ERROR: src dir not found: {src_dir}', file=sys.stderr)
        sys.exit(1)

    tsx_files = sorted(src_dir.rglob('*.tsx')) + sorted(src_dir.rglob('*.ts'))
    tsx_files = [
        f for f in tsx_files
        if not any(p in f.parts for p in ['node_modules', 'dev-dist', '__tests__'])
        and not f.name.endswith('.d.ts')
        and 'vite-env' not in f.name
    ]

    print(f'Scanning {len(tsx_files)} files in {src_dir.relative_to(root)}...')
    files = [parse_file(f, root) for f in tsx_files]
    used_by = build_used_by(files)

    generated_at = datetime.now().strftime('%Y-%m-%d %H:%M')
    md = render_md(files, used_by, generated_at)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding='utf-8')
    print(f'Written: {out_path.relative_to(root)}  ({len(files)} components)')

    ok = verify_map(out_path, root)
    if not ok:
        sys.exit(2)


if __name__ == '__main__':
    main()
